### ISSUE TITLE
TD20240514001 malloc(): corrupted top size

### ISSUE THREAD

**Issue by XBoom** [XBoom/network-ip#11]
Starting program: /home/source/network_ip/apps/ipcs/02/fifo_cli 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[client/client.c:16 main error] fifo_path:./client/1679739/send 
malloc(): corrupted top size

Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007ffff7e49e8f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007ffff7dfafb2 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7de5472 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007ffff7e3e430 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7f58459 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#5  0x00007ffff7e537aa in malloc_printerr (str=str@entry=0x7ffff7f56159 "malloc(): corrupted top size") at ./malloc/malloc.c:5660
#6  0x00007ffff7e56e8b in _int_malloc (av=av@entry=0x7ffff7f91c60 <main_arena>, bytes=44) at ./malloc/malloc.c:4369
#7  0x00007ffff7e579fa in __GI___libc_malloc (bytes=<optimized out>) at ./malloc/malloc.c:3315
#8  0x00007ffff7fa71c3 in write_log (to_type=1, log_type=1, level=0, file=0x555555556015 "client/client.c", lineno=22, 
    func=0x5555555560b7 <__func__.0> "main", format=0x555555556032 "mkfifo failed: %s", ap=0x7fffffffe0c8) at lib_log.c:24
#9  0x00007ffff7fa73ca in log_output (to_type=1, log_type=1, level=0, file=0x555555556015 "client/client.c", lineno=22, 
    func=0x5555555560b7 <__func__.0> "main", format=0x555555556032 "mkfifo failed: %s") at lib_log.c:57
#10 0x0000555555555357 in main (argc=1, argv=0x7fffffffeb38) at client/client.c:22
(gdb) q

**Comment by XBoom** [comment]
使用valgrind 查看日志库的内容泄露情况
[root]#valgrind --leak-check=full ./test 
==1691750== Memcheck, a memory error detector
==1691750== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==1691750== Using Valgrind-3.19.0 and LibVEX; rerun with -h for copyright info
==1691750== Command: ./test
==1691750== 
[main.c:5 show_log info] log info hello 
[main.c:6 show_log error] log error hello 
[main.c:7 show_log warn] log warn hello 
[main.c:8 show_log debug] log debug hello 
[show_log:10]real error
[show_log:11]real info
[show_log:14]log lev 1
[main.c:17 show_log info] log info hello 
==1691750== Invalid write of size 1
==1691750==    at 0x48DB2FC: __vsprintf_internal (iovsprintf.c:98)
==1691750==    by 0x48BBD60: sprintf (sprintf.c:30)
==1691750==    by 0x4858247: write_log (lib_log.c:28)
==1691750==    by 0x48583C9: log_output (lib_log.c:57)
==1691750==    by 0x1093DD: show_log (main.c:18)
==1691750==    by 0x109512: main (main.c:28)
==1691750==  Address 0x4a4b6d7 is 0 bytes after a block of size 39 alloc'd
==1691750==    at 0x48407B4: malloc (vg_replace_malloc.c:381)
==1691750==    by 0x48581C2: write_log (lib_log.c:24)
==1691750==    by 0x48583C9: log_output (lib_log.c:57)
==1691750==    by 0x1093DD: show_log (main.c:18)
==1691750==    by 0x109512: main (main.c:28)
==1691750== 
==1691750== Invalid read of size 1
==1691750==    at 0x49B8420: __strchrnul_avx2 (strchr-avx2.S:55)
==1691750==    by 0x48BF99D: __find_specmb (printf-parse.h:82)
==1691750==    by 0x48BF99D: __vfprintf_internal (vfprintf-internal.c:1092)
==1691750==    by 0x48E1757: __vsnprintf_internal (vsnprintf.c:114)
==1691750==    by 0x4858280: write_log (lib_log.c:32)
==1691750==    by 0x48583C9: log_output (lib_log.c:57)
==1691750==    by 0x1093DD: show_log (main.c:18)
==1691750==    by 0x109512: main (main.c:28)
==1691750==  Address 0x4a4b6d7 is 0 bytes after a block of size 39 alloc'd
==1691750==    at 0x48407B4: malloc (vg_replace_malloc.c:381)
==1691750==    by 0x48581C2: write_log (lib_log.c:24)
==1691750==    by 0x48583C9: log_output (lib_log.c:57)
==1691750==    by 0x1093DD: show_log (main.c:18)
==1691750==    by 0x109512: main (main.c:28)
==1691750== 
==1691750== Invalid read of size 1
==1691750==    at 0x48BFA1E: __vfprintf_internal (vfprintf-internal.c:1098)
==1691750==    by 0x48E1757: __vsnprintf_internal (vsnprintf.c:114)
==1691750==    by 0x4858280: write_log (lib_log.c:32)
==1691750==    by 0x48583C9: log_output (lib_log.c:57)
==1691750==    by 0x1093DD: show_log (main.c:18)
==1691750==    by 0x109512: main (main.c:28)
==1691750==  Address 0x4a4b6d7 is 0 bytes after a block of size 39 alloc'd
==1691750==    at 0x48407B4: malloc (vg_replace_malloc.c:381)
==1691750==    by 0x48581C2: write_log (lib_log.c:24)
==1691750==    by 0x48583C9: log_output (lib_log.c:57)
==1691750==    by 0x1093DD: show_log (main.c:18)
==1691750==    by 0x109512: main (main.c:28)
==1691750== 
[main.c:18 show_log error] log error hello 
[main.c:19 show_log warn] log warn hello 
[main.c:21 show_log debug] log debug 2 hello 
[show_log:22]real error
[show_log:23]real info
==1691750== 
==1691750== HEAP SUMMARY:
==1691750==     in use at exit: 0 bytes in 0 blocks
==1691750==   total heap usage: 9 allocs, 9 frees, 1,334 bytes allocated
==1691750== 
==1691750== All heap blocks were freed -- no leaks are possible
==1691750== 
==1691750== For lists of detected and suppressed errors, rerun with: -s
==1691750== ERROR SUMMARY: 6 errors from 3 contexts (suppressed: 0 from 0)
